### ISSUE TITLE
Canvas Spec should include version for migrations purposes.

### ISSUE THREAD

**Issue by AlyceOsbourne** [obsidianmd/jsoncanvas#41] opened 2024-04-12 14:37 UTC
While I don't foresee the spec changing too often, embedding the spec version into the canvas body would allow for migration handling. 
I also suggest using semantic versioning in this case.

**Comment by kepano** [comment] 2024-04-12 15:10
This is a duplicate of #8

**Closed by kepano** 2024-04-12 15:10 UTC
